FROM node:22-bookworm-slim

ENV NODE_ENV=production

WORKDIR /app

ARG NPM_REGISTRY=https://registry.npmjs.org/

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
COPY modules ./modules

RUN npm config set fetch-retries 5 \
  && npm config set fetch-retry-mintimeout 10000 \
  && npm config set fetch-retry-maxtimeout 120000 \
  && npm config set registry ${NPM_REGISTRY} \
  && npm install -g pnpm@10.0.0 \
  && pnpm config set registry ${NPM_REGISTRY} \
  && pnpm install --frozen-lockfile

ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}

EXPOSE 3000

CMD ["sh", "-c", "pnpm --filter ${SERVICE_NAME} start:prod"]
