FROM node:22-bookworm-slim

ARG SERVICE_NAME
ENV SERVICE_NAME=${SERVICE_NAME}
ENV NODE_ENV=production

WORKDIR /app

COPY package.json pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
COPY modules ./modules

RUN corepack enable && pnpm install --no-frozen-lockfile

EXPOSE 3000

CMD ["sh", "-c", "pnpm --filter ${SERVICE_NAME} start:prod"]
